name: to_do_hive
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  animated_bottom_navigation_bar: ^1.0.0
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.0
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  build_runner: ^2.1.11
  flutter_staggered_grid_view: ^0.6.1
  intl: ^0.17.0
  qr_flutter: ^4.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  hive_generator: ^1.1.3
flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
